# Training and evaluation config
USER_ID_FIELD: user_id
ITEM_ID_FIELD: product_id

load_col: 
inter: ['user_id', 'product_id', 'sum','mean','aisle_id','department_id']

train_neg_sample_args:
    uniform: 1
embedding_size: 128
epochs: 20
train_batch_size: 4096
eval_batch_size: 4096
eval_args:
    group_by: user
    order: TO
    split: {'RS': [0.8,0.1,0.1]}
    mode: full
metrics: ['MRR', 'NDCG', 'Hit']
topk: 20
valid_metric: NDCG@20
metric_decimal_place: 4